### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by g2p** [Lukazoid/lz_diet#5]
Hello,
I've been using the current trunk for a while without issues, I would be happy having it released to crates.io so that my stuff can be released as well.
Thank you!

**Comment by Lukazoid** [comment]
Hi @g2p, glad to hear you are still using the library without issue. 

I will get a version up with your changes (thanks once again!) on crates.io either today or tomorrow as soon as I'm able.

**Comment by Lukazoid** [comment]
Sorry for the delay @g2p had some personal stuff crop up and push this out of my head. Have pushed a new version to crates.io now.

**Comment by g2p** [comment]
Thank you!
